[package]
name = "sid-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
midly = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.5", features = ["derive"] }
